version: '3.3'
services:
  django:
    build: .
    volumes:
      - .:/django/
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=docker
